INSERT INTO COURSE VALUES (1,'Linux&ネットワーク入門');
INSERT INTO COURSE VALUES (2,'データベース入門');
INSERT INTO COURSE VALUES (3,'COBOL基礎');
INSERT INTO COURSE VALUES (4,'Java基礎');
INSERT INTO COURSE VALUES (5,'Webアプリケーション開発入門');
INSERT INTO COURSE VALUES (6,'SEアプリケーション開発入門');
