DROP TABLE USERS;
DROP TABLE CATEGORY;
DROP TABLE ASSIGNMENT;
DROP TABLE PROGRESS;
DROP TABLE COURSE;
DROP TABLE EXERCISE;

CREATE TABLE USERS (USER_ID INT , CATEGORY_ID INT, PASSWORD VARCHAR(64), USER_NAME VARCHAR(32));
CREATE TABLE CATEGORY (CATEGORY_ID INT , CATEGORY_NAME VARCHAR(32));
CREATE TABLE ASSIGNMENT (ASSIGNMENT_ID INT , COURSE_ID INT, ROOM_NO INT, USER_ID INT);
CREATE TABLE PROGRESS (ASSIGNMENT_ID INT , EXERCISE_ID INT , FINISHED_AT DATE);
CREATE TABLE COURSE (COURSE_ID INT , COURSE_NAME VARCHAR(32));
CREATE TABLE EXERCISE (EXERCISE_ID INT , COURSE_ID INT , ORDER_NO INT, EXERCISE_NAME VARCHAR(60));